### ISSUE TITLE
Package path should be relative to the module root directory.

### ISSUE THREAD

**Issue by jstephendix** [pavlosdan/site_studio_webform#1]
https://github.com/pavlosdan/site_studio_webform/blob/33f328da472e323af07956f808bbfd1c580e4550/config/dx8/packages.yml#L1
The paths should be:
```
- config/dx8/cohesion_component_webform.package.yml
- config/dx8/cohesion_component_webform_node.package.yml
```

**Comment by pavlosdan** [comment]
Thanks for catching that ! Merged the PR.
